config/routes.rb
Rails.application.routes.draw do


  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}

  root 'welcome#index'

  get 'preview/:user_id/:repository_id/:revision_id/:path' => 'preview#show', as: :preview, constraints: {path: /.*/}

  # get 'compare' => 'compare#index', as: :compare_index, constraints: {page: /.*/}
  get 'compare(/:type/(:user_id/:repository_id(/:page)))' => 'compare#compare', as: :compare, constraints: {page: /.*/}

  get 'settings' => 'settings#index', as: :settings

  get 'test' => 'welcome#test'

  resources :users do
    resources :repositories do
      member do
        post 'enable'
        post 'disable'
        post 'refresh'
      end

      collection do
        get 'list'
        get 'sync'
      end

      resources :pages do
        collection do
          get 'list'
        end
      end

      resources :revisions do
        collection do
          get 'list'
        end
      end
    end
  end
end

app/views/layouts/_header.html.erb
<header class="alternate">
  <% if user_signed_in? %>
      <div class="header-left">
        <a href="/compare"><h1>Hourglass</h1></a>
      </div>
      <% compare_header ||= false %>
      <% if compare_header %>
          <div class="header-middle">
            <div class="field">
              <input type="search" placeholder="Search"/>
              <button class="search-button"><i class="fa fa-search"></i></button>
            </div>
          </div>
      <% end %>


      <div class="header-right">
        <% if compare_header %>
            <div class="select-compare-type">
              <%= react_component('SelectCompareType') %>
            </div>
        <% end %>

        <h3 class="username"><%= current_user.username %></h3>

        <div class="dropdown">
          <%= link_to 'Settings', settings_path, class: 'button simple-button' %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'button secondary-button' %>
        </div>
      </div>
  <% else %>
      <div class="header-left">
        <a href="/"><h1>Hourglass</h1></a>
      </div>
      <div class="header-middle">

      </div>
      <div class="header-right">
        <%= link_to 'Sign in with Github', user_omniauth_authorize_path(:github), class: 'primary-button' %>
      </div>
  <% end %>
</header>

app/views/layouts/_sidebar.html.erb
<% if user_signed_in? %>
    <%= react_component('Sidebar', {user_id: current_user.id}, {class: 'sidebar-wrapper'}) %>
<% end %>

app/views/layouts/_split_view.html.erb
<aside class="split-view">
  <% if user_signed_in? %>
      <section class="left-side">
        <iframe class="iframe" src="http://wikipedia.com"></iframe>
        <p><span class="left-description"><span title="June 27, 1992 4:05pm EST">2 weeks ago</span> - <b>Graham</b> - Changed the background of the main section to blue</span> <span class="short-hash">e380461</span></p>
      </section><span class="divider"></span></span><section class="right-side">
        <iframe class="iframe" src="http://wikipedia.com"></iframe>
        <p><span class="left-description"><span title="June 27, 1992 4:05pm EST">1 week ago</span> - <b>Carlos</b> - Changed the background of the main section to blue</span> <span class="short-hash">e380461</span></p>
      </section>
  <% else %>
      <%= link_to 'Sign in with Github', user_omniauth_authorize_path(:github) %>
  <% end %>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hourglass</title>

  <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:200,300,400,700' rel='stylesheet' type='text/css'>

  <script>
      var current_user = <%= user_signed_in? ? current_user.id : -1 %>;
  </script>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>


  <%= csrf_meta_tags %>
</head>
<body>
<% compare_header ||= false %>
<%= render partial: 'layouts/header', locals: {compare_header: compare_header} %>
<div class="wrapper">

<% unless hide_sidebar %>
      <%= render 'layouts/sidebar' %>
  <% end %>
  <div id='content' class="content <%= 'no-sidebar' if hide_sidebar %>">
    <%= react_component('Notifications') %>
    <%= yield %>
  </div>
</div>
</body>
</html>

app/views/layouts/compare_header.html.erb
<%= render template: 'layouts/application', locals: {hide_sidebar: false, compare_header: true} %>

app/views/layouts/no_sidebar.html.erb
<%= render template: 'layouts/application', locals: {hide_sidebar: true} %>